[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate --schema=packages/database/prisma/schema.prisma && npx turbo run build --filter=api..."

[deploy]
startCommand = "node apps/api/dist/main.js"
